goals/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path("home/",views.home, name="home" ),
    path("signup",views.signup,name="signup"),
    path("login",views.loginRegister,name="login"),
    path("signout",views.signout,name="signout"),
    path("dashboard",views.dashboard,name="dashboard"),
    path("list",views.goals,name="goals"),
    path('goaldetail/<int:pk>/',views.GoalDetailView.as_view(),name = "goal-detail"),
    path('update-goal/<int:pk>/', views.update_goal, name="update-goal"),
    path('add-goal',views.add_goal,name = "add-goal"),
    path('delete-goal/<int:pk>/',views.deleteGoal,name = "delete-goal"),
    path("accounts",views.accounts_management,name="accounts_management"),
    path("manage-accounts",views.manage_accounts,name="manage-accounts"),
    path("delete-accounts",views.delete_accounts,name="delete-accounts"),
]

goalsvine/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    #path('accounts/', include('allauth.urls')),
    path('goals/', include('goals.urls')),
    path('goalsapi/', include('goalsapi.urls')),
]

goals/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User


STATUS_CHOICES  = (
    ('NS','Not Started'),
    ('IP','In Progress'),
    ('C','Completed'),
)
VISIBILITY_CHOICES = (
    ('PUB','Public'),
    ('PRV','Private')
)
# Create your models here.
    
     
class Goal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    name = models.CharField(max_length=200)
    visibility = models.CharField(choices = VISIBILITY_CHOICES,max_length=20,default='Private')
    status = models.CharField(choices = STATUS_CHOICES,max_length=20,default='Not Started')
    target_date = models.DateTimeField()
    slug = models.SlugField()

    class Meta: 
        ordering = ('-target_date', ) 
    
    def __str__(self):
            return self.name
    
    def get_absolute_url(self):
        return reverse("goal-detail",kwargs={
             'slug':self.slug
        })
    



    

    

    

goals/forms.py
from django import forms # type: ignore
from django.utils import timezone
from django import forms

from goals.models import Goal



STATUS_CHOICES  = (
    ('NS','Not Started'),
    ('IP','In Progress'),
    ('C','Completed'),
)
VISIBILITY_CHOICES = (
    ('PUB','Public'),
    ('PRV','Private')
)

class GoalForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Give the name for the goal','class':'form-group input'}))
    status_option = forms.ChoiceField(widget=forms.Select(attrs={'placeholder':'In Progress','class':'form-group input'}), choices=STATUS_CHOICES)
    target_date = forms.DateTimeField(widget =forms.DateInput(attrs={'type': 'date','class':'form-group'}))
    visibility = forms.ChoiceField(widget=forms.Select(attrs={'placeholder':'Public','class':'form-group'}), choices=VISIBILITY_CHOICES)

    

class AccountForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Username'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':'Email'}))
    password = forms.CharField(widget =forms.TextInput(attrs={'placeholder':'Confrim Password','type': 'password'}))
    confirm_password = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Confrim Password','type': 'password'}))

goals/views.py
from django.shortcuts import get_object_or_404, render,redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required 
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist 
from django.core.mail import send_mail
from django.views import View
from goalsvine  import settings
from goals.forms import GoalForm,AccountForm
from goals.models import  Goal
from django.db import transaction
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView


# Create your views here.
def home(requests):
    return render(requests, "goals/home.html")

def signup(request):
    if request.method == "POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        pass1 = request.POST.get("pass1")
        pass2 = request.POST.get("pass2")

        if User.objects.filter(email=email):
            messages.error(request, "Email already registered")
            return redirect('signup')
        
        if User.objects.filter(username=username):
            messages.error(request, "Username already exists")
            return redirect('signup')
        
        if pass1 != pass2:
            messages.error(request, "Passwords didn't match")
            return redirect('signup')

        myuser = User.objects.create_user(username,email,pass1)
        myuser.save()
        messages.success(request,"Your account has been successfully created")
        return render(request,"goals/goals.html")

    return render(request, "goals/signup.html")

def loginRegister(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('pass1')

        user = authenticate(username=username,password=password)

        if user != None:
            login(request,user)
            return render(request, "goals/dashboard.html")
        
        else:
            messages.error(request,"Invalid username or Password")
            return redirect("login")

        
    return render(request, "goals/signin.html")
@login_required()
def signout(request):
    logout(request)
    messages.success(request,"You have been logged out")
    return redirect("login")

@login_required()
def dashboard(request):
    goals = Goal.objects.filter(user = request.user)
    not_started_goals = Goal.objects.filter(user = request.user,status="NS").count()
    goals_in_progress = Goal.objects.filter(user = request.user,status="IP").count()
    completed_goals = Goal.objects.filter(user = request.user,status="C").count()

    context = { 
        'not_started_goals':not_started_goals,
        'goals_in_progress':goals_in_progress,
        'completed_goals':completed_goals,  
    }
    return render(request,"goals/dashboard.html",context)

@login_required()
def goals(request):
    not_started_goals = Goal.objects.filter(user = request.user,status = "NS")
    goals_inprogress = Goal.objects.filter(user = request.user,status = "IP")
    completed_goals = Goal.objects.filter(user = request.user,status = "C")
    
    context = {
        'not_started_goals':not_started_goals,
        'goals_inprogress':goals_inprogress,
        'completed_goals':completed_goals,
        'goals':goals,
        
    }
    return render(request,"goals/goals.html",context)

class GoalDetailView(DetailView):
    model = Goal
    template_name = "goals/goaldetail.html"
    context_object_name = 'goal'

@login_required()
def update_goal(request, pk):
    goal = get_object_or_404(Goal, id = pk)
    
    if request.method == 'POST':
        form = GoalForm(request.POST)
        if form.is_valid():
            goal.name = form.cleaned_data['name']
            goal.status = form.cleaned_data['status_option']
            goal.visibility = form.cleaned_data['visibility']
            goal.target_date = form.cleaned_data['target_date']
            goal.save()
            return redirect('goal-detail', pk=pk)
    else:
        initial_data = {
            'name': goal.name,
            'status': goal.status,
            'visibility':goal.visibility,
            'deadline': goal.target_date,
        }
        form = GoalForm(initial=initial_data)
    
    return render(request, 'goals/updategoal.html', {'form': form,'goal':goal})

@login_required()
def add_goal(request):
    if request.method == "POST":
        form = GoalForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            status_option = form.cleaned_data["status_option"]
            target_date = form.cleaned_data["target_date"]
            visibility = form.cleaned_data["visibility"]

            goal, created = Goal.objects.get_or_create(
                name=name,
                status=status_option,
                target_date=target_date,
                visibility=visibility,
                user=request.user
            )

            if created:
                messages.success(request, "Goal added successfully.")
            else:
                messages.info(request, "Goal already exists.")
            return redirect("goals")
        else:
            messages.error(request, "There was an error with your form submission.")
    else:
        form = GoalForm()

    return render(request, "goals/add_goal.html", {"form": form})



@login_required()
def deleteGoal(request, pk):
    goal = get_object_or_404(Goal, id=pk, user=request.user)
    goal.delete()
    messages.success(request, "Goal has been deleted")
    return redirect('goals')

@login_required()
def accounts_management(request):
    user_account =  request.user
    return render(request, 'goals/account.html', {'user_account': user_account})

@login_required()
def manage_accounts(request):
    user_account = request.user
    return render(request, 'goals/manage_account.html', {'user_account':user_account})

@login_required()
def delete_accounts(request):
    user_account = User.objects.get()
    user_account.delete()
    return redirect('accounts_management')

goals/templates/goals/account.html
{% extends 'goals/base.html' %}
{% block content %}
<div class="accounts text-center" id="accounts">
    
    <div class="accounts-img">
        <h1>{{ user.email.0 | upper }}</h1>
    </div>
    <h3 class="heading">Hi, <span>{{user.username}}!</span></h3>
    <div class="accounts-content">
        <p>{{user.email}}</p>
        
        <div class="d-flex" style="justify-content: center;">
            <div class="btn-box btns">
                <a href="{% url 'manage-accounts' %}" class="btn"><box-icon name='cog'></box-icon>Manage Account</a>
            </div>

            <div class="btn-box btns">
                <a href="{% url 'delete-accounts' %}" class="btn"><box-icon name='user-plus'></box-icon>Delete Account</a>
            </div>
        </div>
        
        
    </div>
</div>
{% endblock content %}

goals/templates/goals/add_account.html
{% extends "goals/base.html" %}

{% block content %}
<main>
    <div class="container">
      <!-- Navbar -->
        <section class="mb-4">
            <div class="">
                <div class="adjustment column-6  text-center">
                    <h1>Create another account</h1>
                        <form class="login" method="POST" action="{% url 'add-accounts' %}">
                            {% csrf_token %}
                            <div class="input-box">
                                {{form.email}}
                            </div>
                            <div class="input-box">
                                {{form.username}} 
                            </div>
                            <div class="input-box">
                                {{form.password}}
                            </div>
                            <div class="input-box">
                                {{form.confirm_password}}
                            </div>
                            <button class="btn btn-primary" type="submit">Add Account</button>
                        </form>
                
                </div>
            </div>
        </section>
    </div>
</main>
{% endblock content %}

goals/templates/goals/add_goal.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Goal</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'goals/goals.css' %}" />
    <link rel="stylesheet" href="{% static 'goals/styles.css' %}" />
</head>
<body>
    <div class="goal text-center mt-2">
    <h1>Add Goal</h1>
    <form method="post" action="{% url 'add-goal' %}">
        {% csrf_token %}
        {{ form | crispy }}
        <button class="btn btn-primary" type="submit">Add Goal</button>
    </form>
    </div>
</body>
</html>

goals/templates/goals/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <title>{% block head_title %}{% endblock head_title %}</title>
  {% block extra_head %}
  {% endblock extra_head %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'goals/css/bootstrap.min.css'%}" />
  <link rel="stylesheet" href="{% static 'goals/css/mdb.min.css' %}" />
  <link rel="stylesheet" href="{% static 'goals/css/style.css' %}" />
  <link rel="stylesheet" href="{% static 'goals/goals.css' %}" />
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    
</head>

{% include "goals/navbar.html" %}

<body>
    <div class="mt-5 pt-4">
        {% if messages %}
            {% for message in messages %}
                
                <div class="alert alert-{{message.tags}} alert-dismissable fade show" role="alert">
                    {{message}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                    <span aria-hidden="true"></span>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    
    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock extra_body %}

    {% include "goals/footer.html" %}
    {% include "goals/scripts.html" %}
  
</body>
</html>

goals/templates/goals/dashboard.html
{% extends 'goals/base.html' %}
{% block content %} 
    <div id="center" class="main center">
          <div class="mainInner"></div>
          <strong class="ml-5">Dashboard</strong>
    </div>
    
    <div class="goalglide">
        <div class="goals-container">
           
            <div class="text-center">
                <table class="table">
                    <tbody>
                      <tr>
                        <td class="text-center" colspan="4"><h5 class="card-title mt-2">Not Started ({{not_started_goals}}) </h5></td>
                      </tr>
                      <tr>
                        <td class="text-center" colspan="4">There are {{not_started_goals}}  goals available in this section</td>
                      </tr>
                    </tbody>
                  </table>
            </div>
            
            <div class="text-center">
                <table class="table">
                    <tbody>
                      <tr>
                        <td class="text-center" colspan="4"><h5 class="card-title mt-2">In Progress ({{goals_in_progress}}) </h5></td>
                      </tr>
                      <tr>
                        <td class="text-center" colspan="4">There are {{goals_in_progress}} goals available in this section</td>
                      </tr>
                    </tbody>
                  </table>
            </div>
            
            <div class="text-center">
                <table class="table">
                    <tbody>
                      <tr>
                        <td class="text-center" colspan="4"><h5 class="card-title mt-2">Completed ({{completed_goals}})</h5></td>
                      </tr>
                      <tr>
                        <td class="text-center" colspan="4">There are {{completed_goals}} goals available in this section</td>
                      </tr>
                    </tbody>
                  </table>
            </div>
            
        </div>
    </div>
    

{% endblock content %}

goals/templates/goals/footer.html
<footer class="text-center text-white mt-4" style="background-color: #E0E0E0;position: absolute;bottom: 0;width: 100%;">
    <!--<hr class="text-dark">-->
    <!-- Copyright -->
    <div class="copyright text-center p-3" style="background-color: rgba(0, 0, 0, 0.2); color: rgba(0, 0, 0, 0.982)">
        © 2024 Copyright:
        <a class="text-dark"  href="#">Faith</a>
    </div>
      <!-- Copyright -->
</footer>
  

goals/templates/goals/goaldetail.html
{% extends 'goals/base.html' %}
{% block content %} 
<div>
    
    <div class="goal text-center mt-2 justify-content-between">
        <h5 class="text-primary">{{ object.name }}</h5>
        <div class="card-body text-dark">    
            <p>Category: {{ object.category }}</p>
            <div class="visibility d-flex justify-content-between">
                <p class="d-flex"><box-icon name='low-vision'></box-icon>{{ object.get_visibility_display }}</p>
                <p class="d-flex"><box-icon name='radar'></box-icon>{{ object.target_date|date:"d M Y" }}</p>
            </div>
        </div>
        <div class="d-flex justify-content-between">
            <a href="{% url 'delete-goal' goal.id %}" class="btn btn-danger">Delete</a>
            <a href="{% url 'update-goal' goal.id %}" class="btn btn-primary">Update</a>
        </div>
        
    </div>
    
    
</div>
{% endblock content %}

goals/templates/goals/goals.html
{% extends 'goals/base.html' %}
{% block content %} 
    <div id="center" class="main center">
          <!--<div class="mainInner"></div>-->
          <strong class="ml-5">Goals</strong>
          <p>The place where your goals will become a reality</p>
    </div>
    
    <div class="goalglide">
        <div class="goals-container">
            
            <div class="started-goals">
                <h5 class="card-title p-2">Not Started</h5>
                {% for goal in not_started_goals %}
                <div class="">
                    <a href="{% url 'goal-detail' goal.id %}">
                        <div class="goal text-center mt-2">
                            <h5 class="text-primary">{{ goal.name }}</h5>
                            <div class="card-body text-dark">    
                                <p>Category: {{ goal.category }}</p>
                                <div class="visibility d-flex justify-content-between">
                                    <p class="d-flex"><box-icon name='low-vision'></box-icon>{{ goal.get_visibility_display }}</p>
                                    <p class="d-flex"><box-icon name='radar'></box-icon>{{ goal.target_date|date:"d M Y" }}</p>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                
                {% empty %}
            <div class="goal text-center">
                <p class="text-center">No Goals in this Category</p>       
            </div>
                {% endfor %}
            </div>
            
            
            <div class="started-goals">
                <h5 class="card-title p-2">In Progress</h5>
                {% for goal in goals_inprogress %}
                
                <div class="">
                    <a href="{% url 'goal-detail' goal.id %}">
                        <div class="goal text-center mt-2">
                            <h5 class="text-primary">{{ goal.name }}</h5>
                            <div class="card-body text-dark">    
                                <p>Category: {{ goal.category }}</p>
                                <div class="visibility d-flex justify-content-between">
                                    <p class="d-flex"><box-icon name='low-vision'></box-icon>{{ goal.get_visibility_display }}</p>
                                    <p class="d-flex"><box-icon name='radar'></box-icon>{{ goal.target_date|date:"d M Y" }}</p>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                
                {% empty %}
                <div class="goal text-center">
                    <p class="text-center">No Goals in this Category</p>       
                </div>
                {% endfor %}
            </div>
            
            
            <div class="started-goals">
                <h5 class="card-title p-1">Completed</h5>
                {% for goal in completed_goals %}
                <div class="">
                    <a href="{% url 'goal-detail' goal.id %}">
                        <div class="goal text-center mt-2">
                            <h5 class="text-primary">{{ goal.name }}</h5>
                            <div class="card-body text-dark">    
                                <p>Category: {{ goal.category }}</p>
                                <div class="visibility d-flex justify-content-between">
                                    <p class="d-flex"><box-icon name='low-vision'></box-icon>{{ goal.get_visibility_display }}</p>
                                    <p class="d-flex"><box-icon name='radar'></box-icon>{{ goal.target_date|date:"d M Y" }}</p>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                
                {% empty %}
                <div class="goal text-center">
                    <p class="text-center">No Goals in this Category</p>       
                </div>
                {% endfor %}
            </div>
           
        </div>
        <div class="float-right">
            <a href="{% url 'add-goal' %}" class="btn btn-primary">Add New Goal</a> 
        </div>
        
    </div>
    
{% endblock content %}

goals/templates/goals/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Goals</title>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />
    <link rel="stylesheet" href="{% static 'goals/css/bootstrap.min.css'%}" />
    <link rel="stylesheet" href="{% static 'goals/css/mdb.min.css' %}" />
    <!--<link rel="stylesheet" href="{% static 'css/style.css' %}" />-->
    <link rel="stylesheet" href="{% static 'goals/goals.css' %}" />
        
</head>
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-primary">
        <!-- Container wrapper -->
        <div class="container">
        <!-- Toggle button -->
        <!--<button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent1"
            aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>-->

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent1">
            <!-- Navbar brand -->
            <a class="navbar-brand mt-2 mt-sm-0" href="https://mdbootstrap.com/">
            <h3>GoalGlide</h3>
            </a>
            
        </div>
        <!-- Collapsible wrapper -->

        <!-- Right elements -->
        <div class="d-flex align-items-center">
            <!-- Icon -->
            
            <a class="nav-link me-3" href="{% url 'login' %}"> 
                <span class="clearfix d-none d-sm-inline-block">Login</span>
            </a>
            <a class="nav-link me-3" href="{% url 'signup' %}"> 
                <span class="clearfix d-none d-sm-inline-block">SignUp</span>
            </a>
        </div>
        <!-- Right elements -->

        </div>
        <!-- Container wrapper -->
    </nav>
    <body>
        <div class="home">
            <div class="home-container">
                <div class="home-logo align-items-center">
                    <img src="" alt="">
                    <h2>GoalGlide</h2>
                </div>
                
                <div class="home-info">
                    <p>Tracks your goals,motivates and reminds you to convert them to reality</p>
                </div>
            </div>
        </div>
        
          
        <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
        <!-- Custom scripts -->
        <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
    </body>
</html>

goals/templates/goals/manage_account.html
{% extends 'goals/base.html' %}
{% block content %}
<div class="accounts text-center" id="accounts">
    
    <div class="accounts-img">
        <h1>{{ user.email.0 | upper }}</h1>
    </div>
    <h3 class="heading">Welcome, <span>{{user.username}}!</span></h3>
    
</div>
{% endblock content %}

goals/templates/goals/navbar.html
<nav class="navbar  navbar-expand-lg navbar-light bg-white fixed-top">
    <!-- Container wrapper -->  
    <div class="container">
      <div class="">
        <input type="checkbox" class="openSidebarMenu" id="openSidebarMenu">
        <label for="openSidebarMenu" class="sidebarIconToggle">
          <i class="fas fa-bars"></i>
        </label>
        <div id="sidebarMenu">
            <ul class="sidebarMenuInner">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
                <li><a href="{% url 'goals' %}">Goals</a></li>
                <li><a href="#">Category</a></li>
                <li><a href="{% url 'accounts_management' %}">Account</a></li>
                <li><a href="#">Activity</a></li>
                <!--<li><a href="#">Leader Board</a></li>-->
            </ul>
        </div>
      </div>
      <!-- Collapsible wrapper -->
    
        <div class="collapse navbar-collapse" id="navbarSupportedContent1">
          <!-- Navbar brand -->
          <a class="navbar-brand mt-2 mt-sm-0" href="#">
            <img src="" height="20" alt="" loading="lazy" />
            <h3>GoalGlide</h3>
          </a>
        </div>
        <!-- Collapsible wrapper -->

        <!-- Right elements -->
        <div class="d-flex align-items-center">
          <!-- Icon -->
          {% if user.is_authenticated %}
            <div class="d-flex">
              <p class="p-3">Welcome, {{ user.username }}!</p>
              <a class="nav-link me-3" href="{% url 'signout' %}"> 
                <span class="clearfix d-none  d-sm-inline-block ">Logout</span>
              </a>
            </div>

          {% else %}
            <a class="nav-link me-3" href="{% url 'login' %}"> 
              <span class="clearfix d-none d-sm-inline-block">Login</span>
            </a>
            <a class="nav-link me-3" href="{% url 'signup' %}"> 
              <span class="clearfix d-none d-sm-inline-block">SignUp</span>
            </a>
          {% endif %}
        </div>
      
      <!-- Right elements -->
      
    </div>
    <!-- Container wrapper -->
  </nav>

goals/templates/goals/signin.html
{% extends 'goals/base.html' %}
{% block content %}
<main>  
    <div class="container">    
        <section class="mb-4">  
            <div>
                <div class = "adjustment  column-6 0ffset-3 text-center">
                    <h1>Let's sign you In</h1>
                    <form class="login" method="POST" action="{% url 'login' %}">
                        {% csrf_token %}
                        <div class="input-box">
                            <span class="icon"><ion-iconname="mail"></ion-iconname></span>
                            <input class="mb-2" type="text" placeholder="Username" name="username" required>   
                        </div>
                        
                        <div class="input-box">
                            <span class="icon"><ion-iconname="lock-closed"></ion-iconname></span>
                            <input type="password" placeholder="Enter Password" name="pass1" required>
                        </div>
                        
                        <div class="remember-forgot">
                            <label><input type="checkbox">Remember me</label>
                            <a href="#">Forgot Password?</a>
                        </div>
                        
                        <div class="login-register">
                            <p>Don't have an account?<a href="{% url 'signup' %}" class="register-link">Create One</a></p>
                        </div>
                        <button class="btn btn-primary" type="submit">Sign in</button>
                    </form>
            
                </div>
            </div>
        </section>
    </div>
</main>
{% endblock content %}

goals/templates/goals/signup.html
{% extends "goals/base.html" %}

{% block content %}
<main>
    <div class="container">
      <!-- Navbar -->
        <section class="mb-4">
            <div class="">
                <div class="adjustment column-6  text-center">
                    <h1>Let's create your account</h1>
                        <form class="login" method="POST" action="{% url 'signup' %}">
                            {% csrf_token %}
                            <div class="input-box">
                                <span class="icon"><ion-iconname="mail"></ion-iconname></span>
                                <input type="text" placeholder="Username" name="username" required>   
                            </div>
                            <div class="input-box">
                                <span class="icon"><ion-iconname="mail"></ion-iconname></span>
                                <input type="email" placeholder="Email" name="email" required>  
                            </div>
                            <div class="input-box">
                                <span class="icon"><ion-iconname="lock-closed"></ion-iconname></span>
                                <input type="password" placeholder="Enter Password" name="pass1" required>
                            </div>
                            <div class="input-box">
                                <span class="icon"><ion-iconname="lock-closed"></ion-iconname></span>
                                <input type="password" placeholder="Confirm Password" name="pass2" required>
                            </div>
                            <button class="btn btn-primary" type="submit">Sign Up</button>
                        </form>
                
                </div>
            </div>
        </section>
    </div>
</main>
{% endblock content %}